// Autogenerated by Thrift Compiler (0.10.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package userstore

import (
	"bytes"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
	"github.com/twsiyuan/evernote-sdk-golang/types"
	"github.com/twsiyuan/evernote-sdk-golang/errors"

)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var _ = types.GoUnusedProtection__
var _ = errors.GoUnusedProtection__
const EDAM_VERSION_MAJOR = 1
const EDAM_VERSION_MINOR = 28

func init() {
}

