// Autogenerated by Thrift Compiler (0.10.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package notestore

import (
	"bytes"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
	"github.com/twsiyuan/evernote-sdk-golang/userstore"
	"github.com/twsiyuan/evernote-sdk-golang/types"
	"github.com/twsiyuan/evernote-sdk-golang/errors"
	"github.com/twsiyuan/evernote-sdk-golang/limits"

)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var _ = userstore.GoUnusedProtection__
var _ = types.GoUnusedProtection__
var _ = errors.GoUnusedProtection__
var _ = limits.GoUnusedProtection__

func init() {
}

